import type { Applicant } from "@/src/api/types";

export const MOCK_APPLICANTS: Applicant[] = [
  {
    id: "app-1",
    name: "김서연",
    job: "프론트엔드",
    appliedAt: "2026-09-01",
    stage: "document_review",
    finalResult: null,
    version: 1,
  },
  {
    id: "app-2",
    name: "이민준",
    job: "백엔드",
    appliedAt: "2026-09-03",
    stage: "document_review",
    finalResult: null,
    version: 1,
  },
  {
    id: "app-3",
    name: "박지우",
    job: "디자인",
    appliedAt: "2026-08-21",
    stage: "interview",
    finalResult: null,
    version: 1,
  },
  {
    id: "app-4",
    name: "최도윤",
    job: "기획",
    appliedAt: "2026-08-18",
    stage: "interview",
    finalResult: null,
    version: 1,
  },
  {
    id: "app-5",
    name: "정하은",
    job: "데이터",
    appliedAt: "2026-08-02",
    stage: "offer",
    finalResult: null,
    version: 1,
  },
  {
    id: "app-6",
    name: "강서준",
    job: "QA",
    appliedAt: "2026-07-28",
    stage: "offer",
    finalResult: null,
    version: 1,
  },
  {
    id: "app-7",
    name: "조지민",
    job: "프론트엔드",
    appliedAt: "2026-07-10",
    stage: "final",
    finalResult: "passed",
    version: 1,
  },
  {
    id: "app-8",
    name: "윤수아",
    job: "백엔드",
    appliedAt: "2026-07-08",
    stage: "final",
    finalResult: "rejected",
    version: 1,
  },
];
